// constants/safetyResponses.js
// Pre-written, human-authored crisis responses.
//
// CRITICAL SAFETY REQUIREMENT:
//   These strings are NEVER generated by an AI model.
//   They are static constants so a malfunctioning or manipulated AI model
//   cannot alter the crisis response or generate a wrong phone number.
//   Edit this file manually when resource information needs updating.

const CRISIS_RESPONSE = {
  message:
    "I'm really glad you reached out. What you're feeling matters, and you deserve support right now. " +
    "Please consider contacting one of these resources — they are available to help you.",
  resources: [
    {
      name: 'iCall Psychosocial Helpline (India)',
      phone: '9152987821',
      url: 'https://icallhelpline.org',
      available: '8 AM – 10 PM, Mon–Sat',
    },
    {
      name: 'Vandrevala Foundation (India)',
      phone: '1860-2662-345',
      url: 'https://www.vandrevalafoundation.com',
      available: '24/7',
    },
    {
      name: 'NIMHANS Helpline (India)',
      phone: '080-46110007',
      url: 'https://nimhans.ac.in',
      available: 'Business hours',
    },
    {
      name: 'iCall Chat Support',
      phone: null,
      url: 'https://icallhelpline.org/chat',
      available: 'Online',
    },
  ],
  emergency: 'If you are in immediate danger, please call 112 (India) or your local emergency number.',
  disclaimer:
    'MindGuard AI is an educational tool only. For immediate help, please contact a crisis resource above.',
};

const DISTRESS_RESPONSE = {
  message:
    "Thank you for sharing that with me. It sounds like you're going through a difficult time. " +
    "I'm here to listen, and I want you to know you're not alone. " +
    "Would you like to talk about what's on your mind? You can also reach out to a trained counsellor.",
  resources: [
    {
      name: 'iCall Psychosocial Helpline',
      phone: '9152987821',
      url: 'https://icallhelpline.org',
    },
    {
      name: 'Vandrevala Foundation',
      phone: '1860-2662-345',
      url: 'https://www.vandrevalafoundation.com',
    },
  ],
  disclaimer:
    'MindGuard AI provides educational support only. A mental health professional can offer personalised care.',
};

module.exports = { CRISIS_RESPONSE, DISTRESS_RESPONSE };
